### PR TITLE
Fix alienv use in vaf-enter

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@aphecetche, could you try the configuration files from here? They should fix the usage of `alienv`.

**Comment by aphecetche** [comment]
@dberzano well actually we use a slightly modified version of the local.conf, so I did not test directly this PR but the modification of : 

source `which alienv` setenv VO_ALICE@AliPhysics::$VafAliPhysicsVersion

to

eval `alienv printenv VO_ALICE@AliPhysics::$VafAliPhysicsVersion`

and it is working fine.

**Comment by dberzano** [comment]
OK then, I'll merge this. Thanks!

**Comment by dberzano** [comment]
@svallero: does this help fixing your problem?

**Pull request merged**
